engines:
  brakeman:
    enabled: false
  bundler-audit:
    enabled: false
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
        - ruby
        - javascript
  fixme:
    enabled: true
  rubocop:
    enabled: false
ratings:
  paths:
    - Gemfile.lock
    - "**.erb"
    - "**.rb"
    - "**.css"
    - "**.js"
    - "**.jsx"
    - "**.module"
    - "**.php"
    - "**.py"
exclude_paths:
  - "app/javascript/packs/jquery.gridrotator.js"
  - "app/javascript/packs/jquery.placeholder.js"
  - "app/assets/stylesheets/application.css.scss"
  - "app/assets/stylesheets/font-awesome.css.scss"
  - "app/assets/stylesheets/responsive.css.scss"
  - "spec/"
