version: "2"

checks:
  argument-count:
    enabled: true
    config:
      threshold: 4
  complex-logic:
    enabled: true
    config:
      threshold: 4
  file-lines:
    enabled: true
    config:
      threshold: 250
  method-complexity:
    enabled: true
    config:
      threshold: 5
  method-count:
    enabled: true
    config:
      threshold: 20
  method-lines:
    enabled: true
    config:
      threshold: 25
  nested-control-flow:
    enabled: true
    config:
      threshold: 4
  return-statements:
    enabled: true
    config:
      threshold: 4
  similar-code:
    enabled: true
  identical-code:
    enabled: true

plugins:
  brakeman:
    enabled: false
  bundler-audit:
    enabled: false
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 18
        javascript:
          mass_threshold: 45
  fixme:
    enabled: true
  rubocop:
    enabled: false

exclude_patterns:
  - "config/"
  - "db/"
  - "**/node_modules/"
  - "spec/"
  - "**/vendor/"
  - "*.md"
  - "app/assets/images/"
  - ".*"
  - "app/javascript/packs/i18n/"
  - "app/javascript/packs/tailwind.config.js"
  - "babel.config.js"
