engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  duplication:
    enabled: true
    config:
      languages:
      - ruby
      - javascript
      - python
      - php
  fixme:
    enabled: true
  rubocop:
    enabled: true
ratings:
  paths:
    - Gemfile.lock
    - "**.erb"
    - "**.rb"
    - "**.css"
    - "**.js"
    - "**.jsx"
    - "**.module"
    - "**.php"
    - "**.py"
exclude_paths:
  - "app/assets/javascripts/jquery.gridrotator.js"
  - "app/assets/javascripts/jquery.placeholder.js"
  - "spec/"
