engines:
  brakeman:
    enabled: true
  bundler-audit:
    enabled: true
  csslint:
    enabled: true
  eslint:
    enabled: false
  reek:
    enabled: true
  rubocop:
    enabled: true
  scss-lint:
    enabled: true

pull_requests:
  comments: false

exclude_paths:
  - "app/javascript/packs/jquery.gridrotator.js"
  - "app/javascript/packs/jquery.placeholder.js"
  - "app/assets/stylesheets/application.css.scss"
  - "app/assets/stylesheets/font-awesome.css.scss"
  - "spec/"
