detectors:
  UtilityFunction:
    enabled: false
  DuplicateMethodCall:
    max_calls: 2
  IrresponsibleModule:
    enabled: false
  FeatureEnvy:
    enabled: false
  InstanceVariableAssumption:
    exclude:
      - "/Controller$/"
  UncommunicativeMethodName:
    exclude:
      - "Pdf::Format#h1"
      - "Pdf::Format#h2"
      - "Pdf::Format#h3"
      - "Pdf::Format#h5"
  TooManyStatements:
    max_statements: 7

directories:
  "db/migrate":
    TooManyStatements:
      enabled: false

exclude_paths:
  - node_modules
  - lib/seed_manager.rb
  - vendor
