# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

# custom setup
require:
  - rubocop-factory_bot
  - rubocop-rspec
  - rubocop-rspec_rails

AllCops:
  TargetRubyVersion: 3.4
  SuggestExtensions: true
  DisplayCopNames: true
  DisabledByDefault: false
  NewCops: enable

FactoryBot/ExcessiveCreateList:
  Enabled: false

Layout/LineLength:
  Exclude:
    - "config/**/*"

Metrics/BlockLength:
  Exclude:
    - "lib/tasks/*"
    - "spec/**/*"
    - "config/routes.rb"

Metrics/MethodLength:
  Exclude:
    - "db/migrate/*"
    - "lib/seed_manager.rb"

RSpec/NestedGroups:
  Max: 5

Style/Documentation:
  Enabled: false
