require: rubocop-rspec

AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - 'bin/**/*'
    - 'db/schema.rb'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Rails:
  Enabled: true

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '[]'
    '%w': '[]'

Style/StringLiterals:
  Exclude:
    - 'config/**/*'

Documentation:
  Enabled: false

Lint/ScriptPermission:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'lib/tasks/*'
    - 'spec/**/*'

Metrics/LineLength:
  Exclude:
    - 'config/**/*'
    - 'db/migrate/*'
    - 'spec/**/*'

Metrics/MethodLength:
  Exclude:
    - 'db/migrate/*'

Rails/LexicallyScopedActionFilter:
    Enabled: false

RSpec/NestedGroups:
  Max: 5

Style/MixinUsage:
  Enabled: false

Layout/SpaceInsideArrayLiteralBrackets:
  Exclude:
    - 'config/**/*'

FactoryBot/StaticAttributeDefinedDynamically:
  Enabled: false
