AllCops:
  TargetRubyVersion: 2.5
  DisplayCopNames: true
  Exclude:
    - 'db/schema.rb'
    - 'spec/**/*'
    - 'node_modules/**/*'
    - 'vendor/**/*'

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '[]'
    '%w': '[]'

Documentation:
  Enabled: false
