exclude: 'app/assets/stylesheets/admin/mdb/**'

linters:
  Comment:
    enabled: false
  ColorVariable:
    enabled: false
  NestingDepth:
    max_depth: 5
  NameFormat:
    convention: snake_case
  SelectorDepth:
    max_depth: 5
