version: '3.8'

services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    networks:
      - db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: gmmcalcombr_development
    restart: always
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -d postgres" ]
      interval: 30s
      timeout: 10s
      retries: 5

  web:
    build:
      context: .
      target: development
    image: gmmcal:development
    depends_on:
      - db
    networks:
      - db
      - web
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
    ports:
      - "3000:3000"

  cypress:
    build:
      context: .
      target: cypress
    image: gmmcal:cypress
    depends_on:
      - web
    networks:
      - web

networks:
  db:
  web:
