version: '3.7'

services:
  db:
    image: postgres:11.4
    ports:
      - "5432:5432"
    networks:
      - db

  web:
    build:
      context: .
      dockerfile: docker/Dockerfile
    image: gmmcal:latest
    depends_on:
      - db
    networks:
      - db
    volumes:
      - .:/gustavocunha.dev
      - node_modules:/gustavocunha.dev/node_modules
    command: foreman start
    environment:
      RAILS_ENV: development
    ports:
      - "3001:3001"

networks:
  db:

volumes:
  node_modules:
