version: '3.7'

services:
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    networks:
      - db
    environment:
      POSTGRESQL_USERNAME: postgres
      POSTGRESQL_PASSWORD: password
      POSTGRESQL_DATABASE: gmmcalcombr_development
      POSTGRES_HOST_AUTH_METHOD: trust

  web:
    build:
      context: .
      target: development
    image: gmmcal:development
    depends_on:
      - db
    networks:
      - db
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
      DATABASE_USERNAME: postgres
      DATABASE_PASSWORD: password
    ports:
      - "3000:3000"

networks:
  db:
