databases:
  - name: gustavocunha
    databaseName: gustavocunha
    plan: starter
    ipAllowList: []
    region: frankfurt
  - name: gustavocunha-staging
    databaseName: gustavocunha_staging
    plan: free
    ipAllowList: []
    region: frankfurt

services:
  - type: web
    name: gustavocunha
    env: ruby
    runtime: image
    image:
      url: gmmcal/gmmcal:production
    autoDeploy: false
    pullRequestPreviewsEnabled: false
    plan: free
    region: frankfurt
    domains:
      - gustavocunha.dev
      - www.gustavocunha.dev
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gustavocunha
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: gustavocunha
          property: connectionString
      - fromGroup: production
  - type: web
    name: gustavocunha-staging
    env: ruby
    runtime: image
    image:
      url: gmmcal/gmmcal:production
    autoDeploy: false
    pullRequestPreviewsEnabled: false
    plan: free
    region: frankfurt
    domains:
      - staging.gustavocunha.dev
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gustavocunha-staging
          property: connectionString
      - fromGroup: staging
  - type: redis
    name: gustavocunha
    ipAllowList: []
    plan: free
    region: frankfurt
