databases:
  - name: gustavocunha
    databaseName: gustavocunha
    user: gustavocunha
    plan: free
    ipAllowList: []

services:
  - type: web
    name: gustavocunha
    env: ruby
    buildCommand: "bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean; bundle exec rake db:migrate db:seed:all db:cache:clear;"
    startCommand: "bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-development}"
    autoDeploy: true
    pullRequestPreviewsEnabled: true
    plan: free
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gustavocunha
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: gustavocunha
          property: connectionString
      - fromGroup: production
  - type: redis
    name: gustavocunha
    ipAllowList: []
    plan: free
