databases:
  - name: gustavocunha-staging
    databaseName: gustavocunha_staging
    plan: free
    ipAllowList: []
    region: frankfurt

services:
  - type: web
    name: gustavocunha-staging
    env: ruby
    runtime: image
    image:
      url: gmmcal/gmmcal:production
    autoDeploy: false
    pullRequestPreviewsEnabled: false
    plan: free
    region: frankfurt
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gustavocunha-staging
          property: connectionString
      - fromGroup: gmmcal
