databases:
  - name: gustavocunha
    databaseName: gustavocunha
    plan: starter
    ipAllowList: []
    region: frankfurt
  - name: gustavocunha-staging
    databaseName: gustavocunha_staging
    plan: free
    ipAllowList: []
    region: frankfurt

services:
  - type: web
    name: gustavocunha
    env: ruby
    buildCommand: "bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean; bundle exec rake db:migrate db:cache:clear;"
    startCommand: "bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-production}"
    autoDeploy: false
    pullRequestPreviewsEnabled: false
    plan: free
    region: frankfurt
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gustavocunha
          property: connectionString
      - key: REDIS_URL
        fromService:
          type: redis
          name: gustavocunha
          property: connectionString
      - fromGroup: production
  - type: web
    name: gustavocunha-staging
    env: ruby
    buildCommand: "bundle install; bundle exec rake assets:precompile; bundle exec rake assets:clean; bundle exec rake db:migrate db:seed:all db:cache:clear;"
    startCommand: "bundle exec puma -t 5:5 -p ${PORT:-3000} -e ${RACK_ENV:-production}"
    autoDeploy: false
    pullRequestPreviewsEnabled: true
    plan: free
    region: frankfurt
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: gustavocunha-staging
          property: connectionString
      - fromGroup: staging
  - type: redis
    name: gustavocunha
    ipAllowList: []
    plan: free
    region: frankfurt
