service: gmmcal

image: gmmcal/gmmcal

servers:
  web:
    - www.gustavocunha.dev
  db:
    - www.gustavocunha.dev
  job:
    hosts:
      - www.gustavocunha.dev
    cmd: bin/jobs

proxy:
  ssl: true
  hosts:
    - gustavocunha.dev
    - www.gustavocunha.dev

registry:
  username: gmmcal

  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  target: production
  cache:
    type: registry
    options: mode=max
    image: gmmcal/gmmcal.com.br:productioncache

env:
  clear:
    IS_PRODUCTION: true
    RAILS_LOG_TO_STDOUT: enabled
    RAILS_SERVE_STATIC_FILES: enabled
  secret:
    - RAILS_MASTER_KEY
    - DATABASE_USERNAME
    - DATABASE_HOST
    - DATABASE_PASSWORD

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  worker: app logs -f -r worker
  db: app exec --interactive --reuse "bin/rails dbconsole"

asset_path: /rails/public/assets

accessories:
  db:
    image: postgres:16
    roles:
      - db
    port: 5432
    env:
      secret:
        - POSTGRES_USER
        - POSTGRES_DB
        - POSTGRES_PASSWORD
    files:
      - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/postgresql/data
