service: gmmcal

image: gmmcal/gmmcal

proxy:
  ssl: true
  app_port: 3000

registry:
  username: gmmcal

  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  target: production
  cache:
    type: registry
    options: mode=max
    image: gmmcal/gmmcal.com.br:productioncache

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  worker: app logs -f -r worker
  db: app exec --interactive --reuse "bin/rails dbconsole"

asset_path: /rails/public/assets

accessories:
  db:
    image: postgres:16
    roles:
      - db
    port: 5432
    env:
      secret:
        - POSTGRES_USER
        - POSTGRES_DB
        - POSTGRES_PASSWORD
    files:
      - db/production.sql:/docker-entrypoint-initdb.d/setup.sql
    directories:
      - data:/var/lib/postgresql/data
