service: gmmcal

image: gmmcal/gmmcal

proxy:
  ssl: true
  hosts:
    - gustavocunha.dev
    - www.gustavocunha.dev

registry:
  username: gmmcal

  password:
    - KAMAL_REGISTRY_PASSWORD

builder:
  arch: amd64
  target: production
  cache:
    type: registry
    options: mode=max
    image: gmmcal/gmmcal.com.br:productioncache

aliases:
  console: app exec --interactive --reuse "bin/rails console"
  shell: app exec --interactive --reuse "bash"
  logs: app logs -f
  worker: app logs -f -r worker
  db: app exec --interactive --reuse "bin/rails dbconsole"

asset_path: /rails/public/assets
