name: End-to-end Tests

on:
  workflow_call:
    inputs:
      pattern:
        type: string
        required: true
      name:
        type: string
        required: true

jobs:
  e2e:
    name: "End-to-end - ${{ inputs.name }} (${{ matrix.browser }})"
    runs-on: ubuntu-20.04
    container:
      image: gmmcal/gmmcal:cypress
      env:
        CYPRESS_BASE_URL: http://web:3000
        CYPRESS_SPEC_PATTERN: ${{ inputs.pattern }}

    strategy:
      matrix:
        browser: [chrome, firefox]

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: gmmcalcombr_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

      web:
        image: gmmcal/gmmcal:test
        env:
          DATABASE_URL: postgres://postgres:postgres@postgres:5432/gmmcalcombr_test
          ON_CYPRESS: true
        ports:
          - 3000:3000

    steps:
      - name: Run tests on ${{ matrix.browser }}
        run: cypress run --browser ${{ matrix.browser }}
        working-directory: /rails
