name: Deploy application

on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      environment:
        type: string
        required: true
      url:
        type: string
        required: true
      params:
        type: string
        required: false
        default: ""

jobs:
  deploy:
    name: ${{ inputs.name }}
    runs-on: ubuntu-20.04
    environment:
      name: ${{ inputs.environment }}
      url: ${{ inputs.url }}

    steps:
      - name: Deploy
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_SERVICE: ${{ secrets.DEPLOY_SERVICE }}
        run: |
          curl "https://api.render.com/deploy/srv-$DEPLOY_SERVICE?key=$DEPLOY_KEY&${{ inputs.params }}"
