name: Build

on:
  workflow_call:
    inputs:
      name:
        type: string
        required: true
      tag-name:
        type: string
        required: false
        default: "gmmcal/gmmcal:test"
      target:
        type: string
        required: false
        default: test
      reference:
        type: string
        required: false
      publish:
        type: boolean
        required: false
        default: true

jobs:
  build:
    name: ${{ inputs.name }}
    runs-on: ubuntu-20.04

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.reference }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build image
        uses: docker/build-push-action@v5
        with:
          push: ${{ inputs.publish }}
          context: .
          target: ${{ inputs.target }}
          tags: ${{ inputs.tag-name }}
          cache-from: type=registry,ref=gmmcal/gmmcal:buildcache${{ inputs.target }}
          cache-to: type=registry,ref=gmmcal/gmmcal:buildcache${{ inputs.target }},mode=max
