name: Tag application

on:
  workflow_call:
    outputs:
      version:
        description: Prefix of image name
        value: ${{ jobs.tag.outputs.version }}

jobs:
  tag:
    name: Determine tag number
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semver.outputs.next }}

    steps:
      - name: Get Next Version
        id: semver
        uses: ietf-tools/semver-action@v1
        with:
          token: ${{ github.token }}
          noVersionBumpBehavior: patch
          branch: main
          majorList: "BREAK"
          minorList: "NEW"
          patchList: "FIX,OPT"

  create-release:
    name: Release
    uses: ./.github/workflows/_release.yml
    secrets: inherit
    needs: tag
    with:
      tag: ${{needs.tag.outputs.version}}
