name: Backend Tests

on:
  workflow_call:
    inputs:
      command:
        type: string
        required: true

jobs:
  tests:
    name: Backend
    runs-on: ubuntu-20.04
    container:
      image: gmmcal/gmmcal:test
      env:
        DATABASE_URL: postgres://postgres:postgres@postgres:5432/gmmcalcombr_test
        DATABASE_CLEANER_ALLOW_REMOTE_DATABASE_URL: true

    services:
      postgres:
        image: postgres:16
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: gmmcalcombr_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - name: Migrate database
        run: bundle exec rails db:migrate
        working-directory: /rails

      - name: Execute tests
        run: ${{ inputs.command }}
        working-directory: /rails
