name: Cleanup

on:
  workflow_dispatch:
  schedule:
    - cron: "0 2 * * *"

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      # Remove preview environments that are older than 7 days
      - name: Cleanup stale preview environments
        run: |
          curl https://api.render.com/v1/services -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}' -H 'Accept: application/json' | \
          jq -r '.[].service | select(.name | contains("gustavocunha-preview-pr-")) | select(.updatedAt <= (now|strftime("%Y-%m-%dT%H:%M:%SZ") | fromdate - (7*24*60*60)|strftime("%Y-%m-%dT%H:%M:%Z"))) | .id' | \
          xargs -IID curl -X DELETE https://api.render.com/v1/services/ID -H 'Authorization: Bearer ${{ secrets.RENDER_API_KEY }}' -H 'Accept: application/json'
