name: End-to-end tests

on:
  - pull_request

env:
  RAILS_ENV: test

jobs:
  e2e:
    name: Tests
    runs-on: ubuntu-18.04

    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: gmmcalcombr_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1

      # languages
      - name: Install Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.6.5'

      - name: Install Node.js 12.0.0
        uses: actions/setup-node@v1
        with:
          node-version: '12.0.0'

      - name: Install APT dependencies
        run: sudo apt-get -yqq install libpq-dev

      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: ${{ runner.os }}-bundler-e2e-${{ hashFiles('**/Gemfile.lock') }}
          restore-keys: |
            ${{ runner.os }}-bundler-e2e-${{ env.cache-name }}-
            ${{ runner.os }}-bundler-e2e-

      - name: Cache node modules
        uses: actions/cache@v1
        with:
          path: ${{ steps.yarn-cache.outputs.dir }}
          key: ${{ runner.os }}-yarn-e2e-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.os }}-yarn-e2e-${{ env.cache-name }}-
            ${{ runner.os }}-yarn-e2e-

      # dependencies
      - name: Install Bundler gem
        run: gem install bundler
      - name: Run bundle install
        run: |
          bundle config path vendor/bundle
          bundle config set deployment 'true'
          bundle config set without production
          bundle install --jobs 4 --retry 3

      - name: Run yarn install
        run: yarn install

      - name: Setup database
        run: bundle exec rails db:migrate

      # script
      - name: run tests
        uses: cypress-io/github-action@v1
        with:
          start: yarn cypress:ci
