name: Dependabot

on:
  - pull_request

permissions:
  contents: write
  pull-requests: write

jobs:
  run:
    uses: gmmcal/gmmcal-reusable-workflows/.github/workflows/_dependabot.yml@v1
    with:
      pull-request-url: ${{ github.event.pull_request.html_url }}
    secrets:
      token: ${{ secrets.PAT_TOKEN }}
