name: Deploy

on:
  push:
    branches:
      - master
  release:
    types: [published]

env:
  RUBY_VERSION: '2.7.0'

jobs:
  staging:
    name: 'Deploy: Staging'
    runs-on: ubuntu-18.04

    if: github.event_name == 'push'

    container:
      image: ruby:2.7.0

    steps:
      - uses: actions/checkout@v1

      - name: Install dpl gem
        run: |
          gem install dpl --no-document --version "~> 1.10"

      - name: Deploy
        run: |
          dpl --provider=heroku --app=gmmcal-dev --api-key=${{ secrets.HEROKU_API_KEY }}

  production:
    name: 'Deploy: Production'
    runs-on: ubuntu-18.04

    if: github.event_name == 'release'

    container:
      image: ruby:2.7.0

    steps:
      - uses: actions/checkout@v1

      - name: Install dpl gem
        run: |
          gem install dpl --no-document --version "~> 1.10"

      - name: Deploy
        run: |
          dpl --provider=heroku --app=gmmcal --api-key=${{ secrets.HEROKU_API_KEY }}
