name: Deploy

on:
  push:
    branches:
      - main
  release:
    types: [published]
  workflow_call:

jobs:
  build_production:
    name: 'Build: Production'
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      target: production
    concurrency:
      group: build
      cancel-in-progress: true

  build_development:
    name: 'Build: Development'
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      target: development
    if: github.event_name == 'push'
    concurrency:
      group: build
      cancel-in-progress: true

  deploy_staging:
    name: 'Deploy: Staging'
    runs-on: ubuntu-20.04
    environment:
      name: staging
      url: https://staging.gustavocunha.dev
    needs: build_production
    concurrency:
      group: deploy

    steps:
      - name: Deploy
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_SERVICE: ${{ secrets.DEPLOY_SERVICE }}
        run: |
          curl -v "https://api.render.com/deploy/srv-$DEPLOY_SERVICE?key=$DEPLOY_KEY"

  deploy_production:
    name: 'Deploy: Production'
    runs-on: ubuntu-20.04
    environment:
      name: production
      url: https://www.gustavocunha.dev
    needs: deploy_staging
    concurrency:
      group: deploy

    if: github.event_name != 'push'

    steps:
      - name: Deploy
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY }}
          DEPLOY_SERVICE: ${{ secrets.DEPLOY_SERVICE }}
        run: |
          curl -v "https://api.render.com/deploy/srv-$DEPLOY_SERVICE?key=$DEPLOY_KEY"
