name: Deploy

on:
  push:
    branches:
      - main

concurrency:
  group: deploy
  cancel-in-progress: false

jobs:
  tag:
    name: "Tag: Production"
    uses: gmmcal/gmmcal-reusable-workflows/.github/workflows/_tag.yml@v0

  release:
    name: Release
    uses: gmmcal/gmmcal-reusable-workflows/.github/workflows/_release.yml@v0
    secrets: inherit
    needs: tag
    with:
      tag: ${{needs.tag.outputs.version}}

  build_production:
    name: Build
    uses: gmmcal/gmmcal-reusable-workflows/.github/workflows/_docker.yml@v0
    needs:
      - tag
      - release
    secrets: inherit
    with:
      name: Production
      target: production
      reference: ${{needs.tag.outputs.version}}
      tag-name: "gmmcal/gmmcal:${{needs.tag.outputs.version}},gmmcal/gmmcal:production"

  build_development:
    name: Build
    uses: gmmcal/gmmcal-reusable-workflows/.github/workflows/_docker.yml@v0
    secrets: inherit
    with:
      name: Development
      target: development
      tag-name: "gmmcal/gmmcal:development"

  deploy_staging:
    name: Deploy
    uses: gmmcal/gmmcal-reusable-workflows/.github/workflows/_deploy.yml@v0
    secrets: inherit
    needs: build_production
    with:
      name: Staging
      environment: staging
      url: https://staging.gustavocunha.dev

  deploy_production:
    name: Deploy
    uses: gmmcal/gmmcal-reusable-workflows/.github/workflows/_deploy.yml@v0
    secrets: inherit
    needs:
      - build_production
      - tag
    with:
      name: Production
      environment: production
      url: https://www.gustavocunha.dev
      params: imgURL=docker.io/gmmcal/gmmcal:${{needs.tag.outputs.version}}
