name: Deploy

on:
  push:
    branches:
      - master
  release:
    types: [published]

env:
  RUBY_VERSION: '2.7.0'

jobs:
  staging:
    name: 'Deploy: Staging'
    runs-on: ubuntu-18.04

    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v1

      # languages
      - name: Set up RVM
        run: curl -sSL https://get.rvm.io | bash

      - name: Install Ruby ${{ env.RUBY_VERSION }}
        run: |
          source $HOME/.rvm/scripts/rvm
          rvm install ${{ env.RUBY_VERSION }} --binary
          rvm --default use ${{ env.RUBY_VERSION }}

      - name: Install dpl gem
        run: |
          source $HOME/.rvm/scripts/rvm
          gem install dpl --no-document --version "~> 1.10"

      - name: Deploy
        run: |
          source $HOME/.rvm/scripts/rvm
          dpl --provider=heroku --app=gmmcal-dev --api-key=${{ secrets.HEROKU_API_KEY }}

  production:
    name: 'Deploy: Production'
    runs-on: ubuntu-18.04

    if: github.event_name == 'release'

    steps:
      - uses: actions/checkout@v1

      # languages
      - name: Set up RVM
        run: curl -sSL https://get.rvm.io | bash

      - name: Install Ruby ${{ env.RUBY_VERSION }}
        run: |
          source $HOME/.rvm/scripts/rvm
          rvm install ${{ env.RUBY_VERSION }} --binary
          rvm --default use ${{ env.RUBY_VERSION }}

      - name: Install dpl gem
        run: |
          source $HOME/.rvm/scripts/rvm
          gem install dpl --no-document --version "~> 1.10"

      - name: Deploy
        run: |
          source $HOME/.rvm/scripts/rvm
          dpl --provider=heroku --app=gmmcal --api-key=${{ secrets.HEROKU_API_KEY }}
