name: Deploy

on:
  push:
    branches:
      - main
  release:
    types: [published]

jobs:
  staging:
    name: 'Deploy: Staging'
    runs-on: ubuntu-20.04

    if: github.event_name == 'push'

    container:
      image: ruby:3.0.0

    steps:
      - uses: actions/checkout@v1

      - name: Install dpl gem
        run: |
          gem install dpl --no-document --version "~> 1.10"

      - name: Deploy
        run: |
          dpl --provider=heroku --app=gmmcal --api-key=${{ secrets.HEROKU_API_KEY }}

  production:
    name: 'Deploy: Production'
    runs-on: ubuntu-20.04

    if: github.event_name == 'release'

    container:
      image: ruby:3.0.0

    steps:
      - uses: actions/checkout@v1

      - name: Install dpl gem
        run: |
          gem install dpl --no-document --version "~> 1.10"

      - name: Deploy
        run: |
          dpl --provider=heroku --app=gmmcal --api-key=${{ secrets.HEROKU_API_KEY }}
