name: Deploy

on:
  push:
    branches:
      - main
  schedule:
    - cron: "0 0 * * 0"
  release:
    types: [published]

jobs:
  build_production:
    name: 'Build: Production'
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      target: production

  build_development:
    name: 'Build: Development'
    uses: ./.github/workflows/docker.yml
    secrets: inherit
    with:
      target: development
    if: github.event_name == 'push'

  deploy_staging:
    name: 'Deploy: Staging'
    runs-on: ubuntu-20.04
    needs: build_production

    steps:
      - name: Deploy
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY_STAGING }}
          DEPLOY_SERVICE: ${{ secrets.DEPLOY_SERVICE_STAGING }}
        run: |
          curl -v "https://api.render.com/deploy/srv-$DEPLOY_SERVICE?key=$DEPLOY_KEY&ref=$GITHUB_SHA"

  deploy_production:
    name: 'Deploy: Production'
    runs-on: ubuntu-20.04
    needs: deploy_staging

    if: github.event_name != 'push'

    steps:
      - name: Deploy
        env:
          DEPLOY_KEY: ${{ secrets.DEPLOY_KEY_PRODUCTION }}
          DEPLOY_SERVICE: ${{ secrets.DEPLOY_SERVICE_PRODUCTION }}
        run: |
          curl -v "https://api.render.com/deploy/srv-$DEPLOY_SERVICE?key=$DEPLOY_KEY&ref=$GITHUB_SHA"
