name: Deploy

on:
  push:
    branches:
      - master
  release:

jobs:
  staging:
    name: 'Deploy: Staging'
    runs-on: ubuntu-18.04

    if: github.event_name == 'push'

    steps:
      - name: Deploy
        run: echo 'Deploying to Staging'

  production:
    name: 'Deploy: Production'
    runs-on: ubuntu-18.04

    if: github.event_name == 'release'

    steps:
      - name: Deploy
        run: echo 'Deploying to Production'
