name: Deploy

on:
  push:
    # branches:
    #   - master
  release:
    types: [published]

jobs:
  staging:
    name: 'Deploy: Staging'
    runs-on: ubuntu-18.04

    if: github.event_name == 'push'

    container:
      image: ruby:2.7.0

    steps:
      - uses: actions/checkout@v1

      - name: Deploy
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: "gmmcal-dev"
        run: |
          git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git $GITHUB_REF:master

  production:
    name: 'Deploy: Production'
    runs-on: ubuntu-18.04

    if: github.event_name == 'release'

    container:
      image: ruby:2.7.0

    steps:
      - uses: actions/checkout@v1

      - name: Deploy
        env:
          HEROKU_API_TOKEN: ${{ secrets.HEROKU_API_TOKEN }}
          HEROKU_APP_NAME: "gmmcal"
        run: |
          git push https://heroku:$HEROKU_API_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git $GITHUB_REF:master
