name: Deploy

on:
  schedule:
    - cron: "0 0 * * 0"
  release:
    types: [published]

jobs:
  production:
    name: 'Deploy: Production'
    runs-on: ubuntu-20.04

    container:
      image: ruby:3.1.1

    steps:
      - uses: actions/checkout@v1

      - name: Deploy
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
          HEROKU_APP_NAME: gmmcal
        run: |
          git push https://heroku:$HEROKU_API_KEY@git.heroku.com/$HEROKU_APP_NAME.git origin/main:master
