name: Deploy

on:
  push:
  release:

jobs:
  staging:
    name: 'Deploy: Staging'
    runs-on: ubuntu-18.04

    if: github.event_name == 'push'

    steps:
      - uses: actions/checkout@v1

      # languages
      - name: Install Ruby 2.6.x
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: bundler-deploy-staging-1.x
          restore-keys: |
            bundler-deploy-${{ env.cache-name }}-
            bundler-deploy

      - name: Install dpl gem
        run: gem install dpl --version "~> 1.10"

      - name: Deploy
        run: dpl --provider=heroku --app=gmmcal-dev --run="rails db:migrate db:seed:all db:cache:clear" --skip_cleanup --api-key=${{ secrets.HEROKU_API_KEY }}

  production:
    name: 'Deploy: Production'
    runs-on: ubuntu-18.04

    if: github.event_name == 'release'

    steps:
      - uses: actions/checkout@v1

      # languages
      - name: Install Ruby 2.6.x
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Cache gems
        uses: actions/cache@v1
        with:
          path: vendor/bundle
          key: bundler-deploy-staging-1.x
          restore-keys: |
            bundler-deploy-${{ env.cache-name }}-
            bundler-deploy

      - name: Install dpl gem
        run: gem install dpl --version "~> 1.10"

      - name: Deploy
        run: dpl --provider=heroku --app=gmmcal --run="rails db:migrate db:cache:clear" --skip_cleanup --api-key=${{ secrets.HEROKU_API_KEY }}
