name: Frontend unit tests

on:
  - push
  - pull_request

jobs:
  setup:
    name: Setup languages

    steps:
      - name: Install Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

  install:
    name: Install dependencies

    steps:
      - name: Install yarn
        run: npm i -g yarn
      - name: Check yarn version
        run: yarn --version
      - name: Run yarn install
        run: yarn install

  tests:
    name: Frontend Tests
    runs-on: ubuntu-18.04
    needs:
      - setup
      - install

    steps:
      - uses: actions/checkout@v1
      - name: Run tests
        run: yarn test:once
