name: Lint

on:
  workflow_call:
    inputs:
      command:
        type: string
        required: true
      image:
        type: string
        required: false
        default: gmmcal/gmmcal:test

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04

    steps:
      - name: Execute ${{ inputs.command }}
        run: docker run --rm ${{ inputs.image }} ${{ inputs.command }}
