name: Lint

on:
  workflow_call:
    inputs:
      command:
        type: string
        required: true

jobs:
  lint:
    name: Lint
    runs-on: ubuntu-20.04

    steps:
      - name: Execute linter
        run: docker run --rm gmmcal/gmmcal:test ${{ inputs.command }}
