name: backend unit tests
on:
  - push
  - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:11.5
        ports: ["5432:5432"]
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1

      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Install PostgreSQL 11 client
        run: sudo apt-get -yqq install libpq-dev

      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

      - name: Install Bundler gem
        run: gem install bundler
      - name: Install yarn
        run: npm i -g yarn
      - name: Check ruby version
        run: ruby --version
      - name: Check yarn version
        run: yarn --version
      - name: Run bundle install
        run: bundle install --jobs 4 --retry 3
      - name: Run yarn install
        run: yarn install
      - name: Setup database
        run: bundle exec rails db:migrate
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGDATABASE: gmmcalcombr_test
          RAILS_ENV: test

      - name: Run tests
        run: bundle exec rspec
        env:
          PGHOST: localhost
          PGUSER: postgres
          PGDATABASE: gmmcalcombr_test
          RAILS_ENV: test
