name: Backend unit tests

on:
  - push
  - pull_request

env:
  RAILS_ENV: test

jobs:
  setup:
    name: Setup languages

    steps:
      - name: Install Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x

  install:
    name: Install dependencies

    steps:
      - name: Install yarn
        run: npm i -g yarn
      - name: Check yarn version
        run: yarn --version
      - name: Run yarn install
        run: yarn install

  tests:
    name: Backend Tests
    runs-on: ubuntu-18.04

    services:
      postgres:
        image: postgres:11.5
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: gmmcalcombr_test
        ports:
          - 5432:5432
        options: --health-cmd pg_isready --health-interval 10s --health-timeout 5s --health-retries 5

    steps:
      - uses: actions/checkout@v1

      # languages
      - name: Set up Ruby 2.6
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Install PostgreSQL 11 client
        run: sudo apt-get -yqq install libpq-dev

      # dependencies
      - name: Install Bundler gem
        run: gem install bundler
      - name: Check ruby version
        run: ruby --version
      - name: Run bundle install
        run: bundle install --jobs 4 --retry 3
      - name: Setup database
        run: bundle exec rails db:migrate

      # script
      - name: Run tests
        run: bundle exec rspec
